/**:
  ros__parameters:
    mass: 1.0
    trajectory_control:
      antiwindup_cte: 1.0
      alpha: 0.1
      kp:
        x: 10.0
        y: 10.0
        z: 10.0
      ki:
        x: 0.005
        y: 0.005
        z: 0.065
      kd:
        x: 6.0
        y: 6.0
        z: 6.0
      roll_control:
        kp: 20.0
      pitch_control:
        kp: 20.0
      yaw_control:
        kp: 8.0
