world_name: "empty"
origin: 
    latitude: 40.337494
    longitude: -3.883197
    altitude: 100.0
drones:
  - model_type: "quadrotor_base"
    model_name: "drone0"
    flight_time: 60
    xyz:
      - -2.0
      - 0.0
      - 0.2
    payload:
      - model_type: "gps"
        model_name: "gps"
  - model_type: "quadrotor_base"
    model_name: "drone1"
    flight_time: 60
    xyz:
      - 2.0
      - 0.0
      - 0.2
    payload:
      - model_type: "gps"
        model_name: "gps"
  - model_type: "quadrotor_base"
    model_name: "drone2"
    flight_time: 60
    xyz:
      - 0.0
      - 0.0
      - 0.2
    payload:
      - model_type: "gps"
        model_name: "gps"

