
## Arduino and MicroROS

services:
  uros:
    network_mode: "host"
    image: cyberphysics/ros2
    # image: cyberphysics/arduino
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - /dev/shm:/dev/shm
    command: > 
      ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyUSB0 -v 6
  arduino:
    network_mode: "host"
    image: cyberphysics/arduino
    depends_on:
      - uros
    privileged: true
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    devices:
      - /dev:/dev
    command: >
      bash -c "cd Pub && pio run --target upload, monitor"
    restart: "no"
  ros_sub:
    network_mode: "host"
    image: cyberphysics/ros2
    volumes:
      - /dev/shm:/dev/shm
    command: >
      ros2 topic echo --qos-durability=transient_local /micro_ros_arduino_node_publisher std_msgs/msg/Int32
volumes:
  arduino-local:
    external: false
