
## Arduino and MicroROS

services:
  uros:
    network_mode: "host"
    image: microros/micro-ros-agent:jazzy
    # image: cyberphysics/arduino
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - /dev/shm:/dev/shm
    command: > 
      serial --dev /dev/ttyUSB0 -v6
  arduino:
    network_mode: "host"
    image: cyberphysics/arduino
    depends_on:
      - uros
    privileged: true
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    devices:
      - /dev:/dev
    # command: >
    #   bash -c "arduino-cli upload /home/ubuntu/scripts/Pub/Pub.ino --fqbn teensy:avr:teensy41 -p usb3/3-2"
    command: >
      bash -c "arduino-cli compile /home/ubuntu/scripts/Pub/Pub.ino --fqbn teensy:avr:teensy41 -p /dev/ttyACM0 || true"
    # command: >
    #   bash -c "arduino-cli board list"
    restart: "no"
  ros_sub:
    network_mode: "host"
    image: cyberphysics/ros2
    # depends_on:
    #   - arduino
    volumes:
      - /dev/shm:/dev/shm
    command: >
      ros2 topic echo /micro_ros_arduino_node_publisher
volumes:
  arduino-local:
    external: false
