
## Arduino and MicroROS

services:
  uros:
    network_mode: "host"
    image: microros/micro-ros-agent:jazzy
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - /dev/shm:/dev/shm
    command: >
      serial --dev /dev/ttyACM0 -v6
  arduino:
    network_mode: "host"
    image: cyberphysics/arduino
    depends_on:
      - uros
    privileged: true
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - ../applications/arduino/scripts:/home/ubuntu/scripts
      - arduino-local:/home/ubuntu/
    devices:
      - /dev:/dev
    environment:
      - "DISPLAY=${DISPLAY}"
      - XAUTHORITY
      - NVIDIA_DRIVER_CAPABILITIES=all
      - EGL_PLATFORM=surfaceless
    user: "1000:1000"
    command: >
      bash -c "arduino-cli upload /home/ubuntu/scripts/Pub/Pub.ino"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  ros_sub:
    network_mode: "host"
    image: cyberphysics/ros2
    volumes:
      - /dev/shm:/dev/shm
    command: >
      ros2 topic echo /micro_ros_arduino_node_publisher
volumes:
  arduino-local:
    external: false
