
## Arduino and MicroROS

## Connecting uros to the device:
## serial --dev [YOUR BOARD PORT] -v6

## Loading the uros library into the Arduino IDE:
## Sketch -> Include library -> Add .ZIP Library...
## /microrosarduino.zip

## Teensy board support:
## Copy "https://www.pjrc.com/teensy/package_teensy_index.json" 
## Into "File -> Preferences -> Additional boards manager URLs", and click "OK"
## Then "Boards Manager (Icon in left menu) -> teensy -> Install"


services:
  uros:
    network_mode: "host"
    image: microros/micro-ros-agent:jazzy
    privileged: true
    devices:
      - /dev:/dev
    command: >
      serial --dev /dev/ttyACM0 -v6
  arduino:
    network_mode: "host"
    image: cyberphysics/arduino
    depends_on:
      - uros
    privileged: true
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - ../applications/arduino/scripts:/home/ubuntu/scripts
      - arduino-local:/home/ubuntu/
    devices:
      - /dev:/dev
    environment:
      - "DISPLAY=${DISPLAY}"
      - XAUTHORITY
      - NVIDIA_DRIVER_CAPABILITIES=all
      - EGL_PLATFORM=surfaceless
    user: "1000:1000"
    command: >
      bash -c "/opt/arduino-ide/arduino-ide --no-sandbox"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  arduino-local:
    external: false
