services:
  bitnet:
    network_mode: "host"
    image: cyberphysics/bitnet
    container_name: bitnet
    command: >
      stdbuf -o L
      python3 run_inference.py -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf -p "You are a helpful assistant" -cnv
