
services:
  deepresearcher:
    network_mode: "host"
    image: cyberphysics/deepresearcher
    expose:
      - "2024:2024"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - "DISPLAY=${DISPLAY}"
      - XAUTHORITY
      - NVIDIA_DRIVER_CAPABILITIES=all
      - EGL_PLATFORM=surfaceless
      - SEARCH_API=duckduckgo
      - LLM_PROVIDER=ollama 
      - OLLAMA_BASE_URL="http://localhost:11434/" 
      - LOCAL_LLM="qwen3:8b"
    command: >
      bash -c "uvx --refresh --from langgraph-cli[inmem] --with-editable . --python 3.11 langgraph dev --host 0.0.0.0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

