
services:
  deepresearcher:
    image: cyberphysics/deepresearcher
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - "DISPLAY=${DISPLAY}"
      - XAUTHORITY
      - NVIDIA_DRIVER_CAPABILITIES=all
      - EGL_PLATFORM=surfaceless
      - SEARCH_API=duckduckgo
      - TAVILY_API_KEY=tvly-***YOUR_KEY_HERE***
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_URL=http://host.docker.internal:11434/
      - LOCAL_LLM=qwen3:8b
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

# Open in browser:
# https://smith.langchain.com/studio/thread?baseUrl=http://127.0.0.1:2024
