services:
  deerflow:
    network_mode: "host"
    image: cyberphysics/deerflow
    container_name: deerflow
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - "DISPLAY=${DISPLAY}"
      - XAUTHORITY
      - NVIDIA_DRIVER_CAPABILITIES=all
      - "TAVILY_API_KEY=${TAVILY_API_KEY}"
    command: >
      stdbuf -o L
      uv run main.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama:
    volumes:
      - ollama-local:/root/.ollama
    ports:
      - 11434:11434
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]

volumes:
  ollama-local:
    external: false
