services:
  marimo:
    image: cyberphysics/marimo:${CYBERPHYSICS_TAG:-latest}
    container_name: marimo
    network_mode: host
    volumes:
      - ../applications/marimo/notebooks:/notebooks
    environment:
      - MARIMO_WORKDIR=/notebooks
      - MARIMO_HOST=0.0.0.0
      - MARIMO_PORT=2718
    command: >
      marimo edit --headless --host 0.0.0.0 --port 2718 --no-token /notebooks
