# This deployment targets native Ubuntu host

version: "3.9"
services:
  matlab:
    tty: true
    network_mode: "host"
    image: cyberphysics/matlab
    container_name: matlab
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - XAUTHORITY
      - DISPLAY
      - MLM_LICENSE_FILE=/network.lic
      - shm-size=512M
    command: >
        stdbuf -o L
        matlab
