

services:
  ozzmaker: # Ozzmaker IMU, GPS pub
    network_mode: "host"
    image: cyberphysics/ozzmaker
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - /dev/shm:/dev/shm
    command: >
      /scripts/publisher.py
  oak: # Oak-1 ROS feature publisher
    network_mode: "host"
    image: cyberphysics/oak
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - /dev/shm:/dev/shm
    command: >
      /scripts/featuretracker.py
  pyflightcontroller: # FlightController subscribers
    network_mode: "host"
    image: cyberphysics/pyflightcontroller
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - /dev/shm:/dev/shm
    command: >
      /flightcontroller/python/main.py
  vinsmono: # VINS-MONO, only calculate velocity, do I need the whole repo???
    network_mode: "host"
    image: cyberphysics/vinsmono
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - /dev/shm:/dev/shm
    command: >
      ros2 launch vins_estimator.launch.py
  vinsmono: # VINS-MONO, only calculate velocity, do I need the whole repo???
    network_mode: "host"
    image: cyberphysics/vinsmono
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - /dev/shm:/dev/shm
    command: >
      ros2 launch vins_estimator.launch.py
  rangefinder: # laser distance publisher
    network_mode: "host"
    image: cyberphysics/rangefinder
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - /dev/shm:/dev/shm
    command: >
      /scripts/main.py
  behaviortree: # Behavior Tree, obstacle avoidance
    network_mode: "host"
    image: cyberphysics/behaviortree
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - /dev/shm:/dev/shm
    command: >
      /scripts/main.py
  nicegui: # web interface
    network_mode: "host"
    image: cyberphysics/nicegui
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - /dev/shm:/dev/shm
    command: >
      /scripts/main.py
      