
services:
  pyflightcontroller: # FlightController subscribers
    network_mode: "host"
    image: cyberphysics/pyflightcontroller
    privileged: true
    devices:
      - /dev:/dev
    volumes:
      - /dev/shm:/dev/shm
    command: >
      python3 /flightcontroller/python/main.py True
  genesis: # simulator
    network_mode: "host"
    image: cyberphysics/genesis
    privileged: true
    volumes:
      - /dev/shm:/dev/shm
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - "DISPLAY=${DISPLAY}"
      - XAUTHORITY
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: >
      python3 /scripts/vehicle.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
