services:
  oak1_driver:
    image: cyberphysics/oak1
    restart: unless-stopped
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    volumes:
      - /dev/:/dev/
      - /dev/shm:/dev/shm
    privileged: true
    command: >
      stdbuf -o L
      python3 /scripts/megadepth_ros.py --ros-args
        -p device_ip:=${OAK1_DEVICE_IP:-auto}
        -p blob_path:=/models/megadepth_192x256_openvino_2021.4_6shave.blob
        -p image_topic:=/oak1/image_raw
        -p depth_topic:=/oak1/relative_depth
        -p camera_info_topic:=/oak1/camera_info
        -p highres_image_topic:=/oak1/image_highres
        -p highres_camera_info_topic:=/oak1/image_highres/camera_info
        -p highres_capture_hz:=${WILDNAV_IMAGE_RATE:-0.5}

    # --topic-namespace oak1_right --device-ip 10.0.0.12 --rate 30 --debug

    # -v /dev/bus/usb:/dev/bus/usb --device-cgroup-rule='c 189:* rmw'
