
## Ollama:

## Open browser:
## http://localhost:8080/

## Install model:
## Select a model -> Type model name (i.e. llama3.2, qwen2.5-coder:latest, ...) -> Click "pull model ..."

services:
  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    # network_mode: "host"
    pull_policy: missing
    restart: always
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:7869 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_URL=http://localhost:8080
      - WEBUI_NAME=demo
      - WEBUI_SECRET_KEY=demo
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui-local:/app/backend/data

  ollama:
    image: ollama/ollama:latest
    # network_mode: "host"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    pull_policy: missing
    ports:
      - "11434:11434"
      - "7869:7869"
    volumes:
      - ollama-local:/root/.ollama

    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]

volumes:
  ollama-local:
    external: false
  open-webui-local:
    external: false


