
# PySimCoder

services:
  pysimcoder:
    network_mode: "host"
    image: cyberphysics/pysimcoder
    container_name: pysimcoder
    environment:
      - "DISPLAY=${DISPLAY}"
      - XAUTHORITY=/tmp/.XAuthority
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - /dev/shm:/dev/shm
      - ${XAUTHORITY:-/tmp/.Xauthority}:/tmp/.XAuthority:ro
    command: >
      stdbuf -o L
      psc
      