# This deployment targets native Ubuntu host

version: "3.9"
services:
  qgroundcontrol:
    network_mode: "host"
    image: cyberphysics/qgroundcontrol
    container_name: qgroundcontrol
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - "DISPLAY=${DISPLAY}"
    depends_on:
      - roscore
    command: >
      stdbuf -o L
      bash -c "./staging/QGroundControl"

