services:
  so101_cbf:
    image: cyberphysics/so101:latest
    container_name: so101_cbf
    network_mode: host
    ipc: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    command: ros2 run so101_description so101_cbf_control.py

  so101_gym:
    image: cyberphysics/so101:latest
    container_name: so101_gym
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    command: python3 /workspace/src/so101_description/scripts/run_gym_hil.py
