
# SpaceROS

services:
  spaceros:
    network_mode: "host"
    image: cyberphysics/spaceros
    container_name: spaceros
    environment:
      - "DISPLAY=${DISPLAY}"
      - XAUTHORITY=/tmp/.XAuthority
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    volumes:
      - /dev/shm:/dev/shm
      - $XAUTHORITY:/tmp/.XAuthority
    command: >
      stdbuf -o L
      /demos/curiosity_rover/run.sh
      